### ISSUE TITLE
Casing for parameters

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Plots#18]
@KatrinCoboeken @Yuri05 
During the demo last week, I saw that some parameters were spelt using PascalCase and some others were using CamelCase

I think we should be consistent and have all parameters be camelCase  =>
myParameter and not MyParameter

I don't remember where but it was not definitely not always consistent

**Comment by KatrinCoboeken** [comment]
I'm normally using CamelCase, 
If I find some PascalCase parameters I will change them.

**Comment by Yuri05** [comment]
`lint_package(linters=object_name_linter(styles = c("camelCase", "symbols")))`
might help :)

**Comment by KatrinCoboeken** [comment]
I have testted the code with lint, and there werent any issuses with PascalCase.
I tested it by   introducing a new dummy Parameter "MyParam = 4", and got a lint marker, so in principal it seems to work.

I totally agree with Michael that we should use CamelCode consistently and try to do it.

**Comment by msevestre** [comment]
ok then :) All good
