### ISSUE TITLE
crash of vignettes

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/OSPSuite.Plots#3]
Vignettes crashed during overnight test

**Comment by Yuri05** [comment]
closing the issue 
(@KatrinCoboeken please add "Fixes #NNN" in a commit/PR which fixes the issue #NNN) - then it will be closed automatically when the corresponding PR was merged (s. [Linking a pull request to an issue using a keyword](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))
